/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_934763_5_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_934763_1[] = { "banana", "cinnamon", "coconut", "empty" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_934763_4_axes[] = { 0, 1, 2, 3, 4 };
const uint32_t ei_dsp_config_934763_4_axes_size = 5;
ei_dsp_config_flatten_t ei_dsp_config_934763_4 = {
    4, // uint32_t blockId
    1, // int implementationVersion
    5, // int length of axes
    1.0f, // float scale-axes
    true, // boolean average
    true, // boolean minimum
    true, // boolean maximum
    true, // boolean rms
    true, // boolean stdev
    true, // boolean skewness
    true, // boolean kurtosis
    0 // int moving_avg_num_windows
};

const float ei_dn_standard_scaler_mean_934763_4[35] = { 22.243542646270953, 22.2418627676621, 22.24524512945437, 22.24354269301969, 0.0014128278985808245, 0.004872748043233669, -1.8667723331965653, 41.95359140907238, 41.89423196456011, 42.01348027372672, 41.953678723254235, 0.039183781133033335, 0.027707072974651942, -1.1698570096092238, 66.07009809780745, 66.0016339869281, 66.1421568627451, 66.07033630445892, 0.05741863751333524, 0.009125709971960853, -2.5912611005352995, 704.0202603807636, 703.3333333333334, 704.8643790849674, 704.020590688668, 0.5459901384181447, 0.31025960604094116, -0.3470681780580967, 7.459803911303383, 7.119281051595227, 7.8016339878436005, 7.466089688387572, 0.22711048348885932, 0.04358535797474997, -1.3222700417394828 };
const float ei_dn_standard_scaler_scale_934763_4[35] = { 4.4117139974352435, 4.415214639258809, 4.40902650834669, 4.411712366148678, 490.2435493793158, 1.1237045118774018, 0.4401350086425091, 0.12429671551747438, 0.12500274541518144, 0.12357734480744677, 0.1242951750394029, 11.626320574358662, 1.2541944658219357, 0.5708848173278989, 0.028823443361353115, 0.02883841096238108, 0.02880969645948025, 0.028823498962825732, 6.516420598187026, 1.9395421512561375, 0.7068043605748832, 0.027682760108552612, 0.027662368043671906, 0.027673135413403074, 0.02768279920392443, 2.476842414725124, 0.8695627987352278, 0.41067996622668856, 0.1538905173845055, 0.16163128043962843, 0.14700948513635753, 0.15378190916542908, 3.1325683956206647, 1.4225512768755852, 0.6242233055390899 };
const float ei_dn_standard_scaler_var_934763_4[35] = { 0.05137895886172891, 0.05129751863949556, 0.05144161327035852, 0.05137899685777846, 0.000004160794092273333, 0.7919463302954924, 5.162120902298923, 64.72628698261853, 63.99718878746989, 65.4820520372808, 64.72789138992715, 0.007398018494578717, 0.6357263896234526, 3.0683366939761907, 1203.6723264552243, 1202.4231999444619, 1204.8212946943513, 1203.6676826130988, 0.02354950508209842, 0.2658285089173315, 2.0017118474471274, 1304.9119896469904, 1306.836601307191, 1305.819842261523, 1304.9083038937526, 0.16300587136990713, 1.3225073569778152, 5.929157196786894, 42.22564386218005, 38.277994276825616, 46.27104276065521, 42.28530850608954, 0.10190579371578865, 0.4941560767961782, 2.566374561168378 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_934763_4 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_934763_4,
    .mean_data_len = 35,
    .scale_data = (float *)ei_dn_standard_scaler_scale_934763_4,
    .scale_data_len = 35,
    .var_data = (float *)ei_dn_standard_scaler_var_934763_4,
    .var_data_len = 35
};
ei_data_normalization_t ei_data_normalization_config_934763_4 = {
    (void *) &ei_data_normalization_standard_scaler_config_934763_4, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_934763_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_934763_1[ei_dsp_blocks_934763_1_size] = {
    { // DSP block 4
        4,
        35, // output size
        &extract_flatten_features, // DSP function pointer
        (void*)&ei_dsp_config_934763_4, // pointer to config struct
        ei_dsp_config_934763_4_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_934763_4_axes_size, // number of axes
        1, // version
        flatten_class::create, // factory function
        &ei_data_normalization_config_934763_4, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_934763_5 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_934763_5_init,
    .model_invoke = &tflite_learn_934763_5_invoke,
    .model_reset = &tflite_learn_934763_5_reset,
    .model_input = &tflite_learn_934763_5_input,
    .model_output = &tflite_learn_934763_5_output,
};

const uint8_t ei_output_tensors_indices_934763_5[1] = { 0 };
const uint8_t ei_output_tensors_size_934763_5 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_934763_5 = {
    .implementation_version = 1,
    .block_id = 5,
    .output_tensors_indices = ei_output_tensors_indices_934763_5,
    .output_tensors_size = ei_output_tensors_size_934763_5,
    .quantized = 0,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_934763_5,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_934763_1_size = 1;
const uint32_t ei_learning_block_934763_5_inputs[1] = { 4 };
const uint8_t ei_learning_block_934763_5_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_934763_1[ei_learning_blocks_934763_1_size] = {
    {
        5,
        &run_nn_inference,
        (void*)&ei_learning_block_config_934763_5,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_934763_5_inputs,
        ei_learning_block_934763_5_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_934763_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_934763_1[ei_postprocessing_blocks_934763_1_size] = {
    {
        .block_id = 5,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_f32,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 5
    },
};

const uint8_t freeform_outputs_934763_1_size = 0;

uint32_t *freeform_outputs_934763_1 = nullptr;

const ei_impulse_t impulse_934763_1 = {
    .project_id = 934763,
    .project_owner = "pablo824",
    .project_name = "Research_Days_Enose",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 10,

    .nn_input_frame_size = 35,
    .raw_sample_count = 10,
    .raw_samples_per_frame = 5,
    .dsp_input_frame_size = 10 * 5,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1000,
    .frequency = 1,

    .dsp_blocks_size = ei_dsp_blocks_934763_1_size,
    .dsp_blocks = ei_dsp_blocks_934763_1,

    .learning_blocks_size = ei_learning_blocks_934763_1_size,
    .learning_blocks = ei_learning_blocks_934763_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_934763_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_934763_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "temp_sen66 + humidity_sen66 + vocIndex + CO2 + HCHO",
    .slice_size = (10/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 4,
    .categories = ei_classifier_inferencing_categories_934763_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_934763_1_size,
    .freeform_outputs = freeform_outputs_934763_1
};

ei_impulse_handle_t impulse_handle_934763_1 = ei_impulse_handle_t( &impulse_934763_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_934763_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_934763_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_934763_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_934763_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
